# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Component.create(name: "Bulletproof Glass")
Component.create(name: "Canvas")
Component.create(name: "Large Steel Tube")
Component.create(name: "Computer")
Component.create(name: "Construction Component")
Component.create(name: "Detector Component")
Component.create(name: "Display")
Component.create(name: "Explosives")
Component.create(name: "Girder")
Component.create(name: "Gravity Generator Component")
Component.create(name: "Interior Plate")
Component.create(name: "Medical Component")
Component.create(name: "Metal Grid")
Component.create(name: "Motor")
Component.create(name: "Power Cell")
Component.create(name: "Radio-Communication Component")
Component.create(name: "Reactor Component")
Component.create(name: "Reactor Component")
Component.create(name: "Small Steel Tube")
Component.create(name: "Solar Cell")
Component.create(name: "Steel Plate")
Component.create(name: "Superconductor Component")
Component.create(name: "Thruster Comoponent")
Component.create(name: "Zone Chip")

Block.create(name: "Light Armor Block", category: "Armor (Light)", size: "Large")
Block.create(name: "Light Armor Block", category: "Armor (Light)", size: "Small")
Block.create(name: "Heavy Armor Block", category: "Armor (Heavy)", size: "Large")
Block.create(name: "Heavy Armor Block", category: "Armor (Heavy)", size: "Small")
Block.create(name: "Programmable block", category: "Automation", size: "Large")
Block.create(name: "Programmable block", category: "Automation", size: "Small")
Block.create(name: "Sensor", category: "Automation", size: "Either")
Block.create(name: "Sound Block", category: "Automation", size: "Either")
Block.create(name: "Button Panel", category: "Automation", size: "Large")
Block.create(name: "Button Panel", category: "Automation", size: "Small")
Block.create(name: "Timer Block", category: "Automation", size: "Large")
Block.create(name: "Timer Block", category: "Automation", size: "Small")
Block.create(name: "Oxygen Tank", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Oxygen Tank", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Hydrogen Tank", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Hydrogen Tank", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Small Hydrogen Tank", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Small Hydrogen Tank", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Air Vent", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Air Vent", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Large Cargo Container", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Large Cargo Container", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Medium Cargo Container", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Small Cargo Container", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Small Cargo Container", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Conveyor Junction", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Conveyor Junction", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Small Conveyor", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Conveyor Tube", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Medium Conveyor Tube", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Small Conveyor Tube", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Conveyor Frame", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Curved Conveyor Tube", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Curved Conveyor Tube", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Small Curved Conveyor Tube", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Conveyor Sorter", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Conveyor Sorter", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Small Conveyor Sorter", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Connector", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Connector", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Ejector", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Collector", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Collector", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Flight Seat", category: "Cockpit / Control", size: "Large")
Block.create(name: "Control Stations", category: "Cockpit / Control", size: "Large")
Block.create(name: "Cockpit", category: "Cockpit / Control", size: "Small")
Block.create(name: "Cockpit", category: "Cockpit / Control", size: "Large")
Block.create(name: "Passenger Seat", category: "Cockpit / Control", size: "Either")
Block.create(name: "Fighter Cockpit", category: "Cockpit / Control", size: "Small")
Block.create(name: "Control Seat", category: "Cockpit / Control", size: "Small")
Block.create(name: "Control Seat", category: "Cockpit / Control", size: "Large")
Block.create(name: "Control Panel", category: "Cockpit / Control", size: "Either")
Block.create(name: "Gyroscope", category: "Cockpit / Control", size: "Large")
Block.create(name: "Gyroscope", category: "Cockpit / Control", size: "Small")
Block.create(name: "Antenna", category: "Communications", size: "Large")
Block.create(name: "Antenna", category: "Communications", size: "Small")
Block.create(name: "Antenna Dish", category: "Communications", size: "Large")
Block.create(name: "Beacon", category: "Communications", size: "Large")
Block.create(name: "Beacon", category: "Communications", size: "Small")
Block.create(name: "Remote Control", category: "Communications", size: "Small")
Block.create(name: "Remote Control", category: "Communications", size: "Large")
Block.create(name: "Laser Antenna", category: "Communications", size: "Large")
Block.create(name: "Laser Antenna", category: "Communications", size: "Small")
Block.create(name: "", category: "", size: "")

BlockComponent.create(block_id: 1, component_id: 1, number_of_components: 20)