# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Component.create(name: "Bulletproof Glass")
Component.create(name: "Canvas")
Component.create(name: "Large Steel Tube")
Component.create(name: "Computer")
Component.create(name: "Construction Component")
Component.create(name: "Detector Component")
Component.create(name: "Display")
Component.create(name: "Explosives")
Component.create(name: "Girder")
Component.create(name: "Gravity Generator Component")
Component.create(name: "Interior Plate")
Component.create(name: "Medical Component")
Component.create(name: "Metal Grid")
Component.create(name: "Motor")
Component.create(name: "Power Cell")
Component.create(name: "Radio-Communication Component")
Component.create(name: "Reactor Component")
Component.create(name: "Reactor Component")
Component.create(name: "Small Steel Tube")
Component.create(name: "Solar Cell")
Component.create(name: "Steel Plate")
Component.create(name: "Superconductor Component")
Component.create(name: "Thruster Comoponent")
Component.create(name: "Zone Chip")

Block.create(name: "Light Armor Block", category: "Armor (Light)", size: "Large")
Block.create(name: "Light Armor Block", category: "Armor (Light)", size: "Small")
Block.create(name: "Heavy Armor Block", category: "Armor (Heavy)", size: "Large")
Block.create(name: "Heavy Armor Block", category: "Armor (Heavy)", size: "Small")
Block.create(name: "Programmable block", category: "Automation", size: "Large")
Block.create(name: "Programmable block", category: "Automation", size: "Small")
Block.create(name: "Sensor", category: "Automation", size: "Either")
Block.create(name: "Sound Block", category: "Automation", size: "Either")
Block.create(name: "Button Panel", category: "Automation", size: "Large")
Block.create(name: "Button Panel", category: "Automation", size: "Small")
Block.create(name: "Timer Block", category: "Automation", size: "Large")
Block.create(name: "Timer Block", category: "Automation", size: "Small")
Block.create(name: "Oxygen Tank", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Oxygen Tank", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Hydrogen Tank", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Hydrogen Tank", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Small Hydrogen Tank", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Small Hydrogen Tank", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Air Vent", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Air Vent", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Large Cargo Container", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Large Cargo Container", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Medium Cargo Container", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Small Cargo Container", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Small Cargo Container", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Conveyor Junction", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Conveyor Junction", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Small Conveyor", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Conveyor Tube", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Medium Conveyor Tube", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Small Conveyor Tube", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Conveyor Frame", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Curved Conveyor Tube", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Curved Conveyor Tube", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Small Curved Conveyor Tube", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Conveyor Sorter", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Conveyor Sorter", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Small Conveyor Sorter", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Connector", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Connector", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Ejector", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Collector", category: "Conveyor / Cargo", size: "Small")
Block.create(name: "Collector", category: "Conveyor / Cargo", size: "Large")
Block.create(name: "Flight Seat", category: "Cockpit / Control", size: "Large")
Block.create(name: "Control Stations", category: "Cockpit / Control", size: "Large")
Block.create(name: "Cockpit", category: "Cockpit / Control", size: "Small")
Block.create(name: "Cockpit", category: "Cockpit / Control", size: "Large")
Block.create(name: "Passenger Seat", category: "Cockpit / Control", size: "Either")
Block.create(name: "Fighter Cockpit", category: "Cockpit / Control", size: "Small")
Block.create(name: "Control Seat", category: "Cockpit / Control", size: "Small")
Block.create(name: "Control Seat", category: "Cockpit / Control", size: "Large")
Block.create(name: "Control Panel", category: "Cockpit / Control", size: "Either")
Block.create(name: "Gyroscope", category: "Cockpit / Control", size: "Large")
Block.create(name: "Gyroscope", category: "Cockpit / Control", size: "Small")
Block.create(name: "Antenna", category: "Communications", size: "Large")
Block.create(name: "Antenna", category: "Communications", size: "Small")
Block.create(name: "Antenna Dish", category: "Communications", size: "Large")
Block.create(name: "Beacon", category: "Communications", size: "Large")
Block.create(name: "Beacon", category: "Communications", size: "Small")
Block.create(name: "Remote Control", category: "Communications", size: "Small")
Block.create(name: "Remote Control", category: "Communications", size: "Large")
Block.create(name: "Laser Antenna", category: "Communications", size: "Large")
Block.create(name: "Laser Antenna", category: "Communications", size: "Small")
Block.create(name: "Bed", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Desk", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Desk Corner", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Chairless Desk", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Chairless Desk Corner", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Couch", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Corner Couch", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Kitchen", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Planters", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Armory", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Armory Lockers", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Lockers", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Toilet", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Bathroom", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Toilet Seat", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Console Block", category: "Decorative Blocks DLC", size: "Large")
Block.create(name: "Industrial Cockpit", category: "Cockpit / Control", size: "Large")
Block.create(name: "Industrial Cockpit", category: "Cockpit / Control", size: "Small")
Block.create(name: "Dispenser", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Jukebox", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Lab Equipment", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Shower", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Window Wall", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Window Wall Left", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Window Wall Right", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Medical Station", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Transparent LCD", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Grated Catwalk", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Grated Catwalk Corner", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Grated Catwalk Straight", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Grated Catwalk Wall", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Grated Catwalk End", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Grated Catwalk Half Right", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Grated Catwalk Half Left", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Grated stairs", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Grated half stairs", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Grated half stairs mirrored", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Railing Straight", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Railing Double", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Railing Corner", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Railing Diagonal", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Railing Half Right", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Railing Half Left", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Rotating Light", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Rotating Light", category: "Decorative Blocks 2 DLC", size: "Small")
Block.create(name: "Freight 1", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Freight 2", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Freight 3", category: "Decorative Blocks 2 DLC", size: "Large")
Block.create(name: "Door", category: "Doors", size: "Large")
Block.create(name: "Airtight Hangar Door", category: "Doors", size: "Large")
Block.create(name: "Sliding Door", category: "Doors", size: "Large")
Block.create(name: "Blast doors", category: "Doors", size: "Large")
Block.create(name: "Blast dooor corner", category: "Doors", size: "Large")
Block.create(name: "Blast door corner inverted", category: "Doors", size: "Large")
Block.create(name: "Blast door edge", category: "Doors", size: "Large")
Block.create(name: "Gate", category: "Doors", size: "Large")
Block.create(name: "Offset Door", category: "Doors", size: "Large")
Block.create(name: "Store", category: "Economy", size: "Large")
Block.create(name: "Contracts", category: "Economy", size: "Large")
Block.create(name: "Vending Machine", category: "Economy", size: "Large")
Block.create(name: "ATM", category: "Economy", size: "Large")
Block.create(name: "Safe Zone", category: "Economy", size: "Large")
Block.create(name: "", category: "Frostbite DLC", size: "Large")
Block.create(name: "Dead Engineers", category: "Frostbite DLC", size: "Large")
Block.create(name: "Gravity Generator", category: "Gravity", size: "Large")
Block.create(name: "Spherical Gravity Generator", category: "Gravity", size: "Large")
Block.create(name: "Artificial Mass", category: "Gravity", size: "Large")
Block.create(name: "Artificial Mass", category: "Gravity", size: "Small")
Block.create(name: "Space Ball", category: "Gravity", size: "Large")
Block.create(name: "Space Ball", category: "Gravity", size: "Small")
Block.create(name: "Passage", category: "Interiors", size: "Large")
Block.create(name: "Stairs", category: "Interiors", size: "Large")
Block.create(name: "Ramp", category: "Interiors", size: "Large")
Block.create(name: "Steel Catwalk", category: "Interiors", size: "Large")
Block.create(name: "Steel Catwalk Two Sides", category: "Interiors", size: "Large")
Block.create(name: "Steel Catwalk Corner", category: "Interiors", size: "Large")
Block.create(name: "Steel Catwalk Plate", category: "Interiors", size: "Large")
Block.create(name: "Cover Walls", category: "Interiors", size: "Large")
Block.create(name: "Half Cover Wall", category: "Interiors", size: "Large")
Block.create(name: "Interior Wall", category: "Interiors", size: "Large")
Block.create(name: "Interior Pillar", category: "Interiors", size: "Large")
Block.create(name: "Ladder", category: "Interiors", size: "Large")
Block.create(name: "", category: "", size: "Large")

BlockComponent.create(block_id: 1, component_id: 1, number_of_components: 20)